export const FETCH_PODCASTS_LIST_REQUEST = 'FETCH_PODCASTS_LIST_REQUEST'
export const FETCH_PODCASTS_LIST_SUCCESS = 'FETCH_PODCASTS_LIST_SUCCESS'
export const FETCH_PODCASTS_LIST_FAILURE = 'FETCH_PODCASTS_LIST_FAILURE'

export const FETCH_PODCAST_BY_ID_REQUEST = 'FETCH_PODCAST_BY_ID_REQUEST'
export const FETCH_PODCAST_BY_ID_SUCCESS = 'FETCH_PODCAST_BY_ID_SUCCESS'
export const FETCH_PODCAST_BY_ID_FAILURE = 'FETCH_PODCAST_BY_ID_FAILURE'
